server: 
  port: 9001
spring: 
  application:  
    name: tensqure-base #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/tensqure_base?characterEncoding=UTF8&&serverTimezone=UTC
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
